export const reports = [
  {
    id: 1,
    title: "Street Flooding",
    location: "Lianga, Surigao Del Sur",
    time: "2 hours ago",
    status: "Under Review",
    statusColor: "bg-yellow-100",
    statusTextColor: "text-yellow-800",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUGPe6qvJr0369R1iFkaGhDx6LDEa1bjrAuA&s",
    description: "Water level reaching knee height at Commonwealth Ave.",
    messages: 2,
  },
  {
    id: 2,
    title: "House Fire",
    location: "Lianga, Surigao Del Sur",
    time: "5 hours ago",
    status: "Resolved",
    statusColor: "bg-green-100",
    statusTextColor: "text-green-800",
    image: "https://cdn.sanity.io/images/ycvw0l8e/production/b60207faf3c300ab95d4d67eccc3175c1e74da9d-4800x2700.jpg",
    description: "Fire at residential area, smoke visible from street.",
    messages: 8,
  },
  {
    id: 3,
    title: "Road Blockage",
    location: "Lianga, Surigao Del Sur",
    time: "1 day ago",
    status: "In Progress",
    statusColor: "bg-blue-100",
    statusTextColor: "text-blue-800",
    image: "https://media.philstar.com/images/articles/gen11-otis-bridge-eddgumban2018-06-2722-44-58_2018-09-05_12-40-12.jpg",
    description: "Fallen tree blocking the main road after heavy rain.",
    messages: 5,
  },
];